{
    "name": "Instalacje24 Office",
    "summary": "Biuro hydraulika: CRM, wyceny i automatyzacja sprzedaży",
    "version": "17.0.2.0.0",
    "category": "Sales",
    "author": "Instalacje24",
    "license": "LGPL-3",
    "depends": ["base", "contacts", "sale_management", "account", "calendar", "instalacje24_terrain"],
    "data": [
        "security/instalacje24_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/cron_data.xml",
        "views/menu_views.xml",
        "views/lead_views.xml",
        "views/quote_views.xml",
        "views/dashboard_views.xml",
        "views/res_config_settings_views.xml",
        "views/quick_job_wizard_views.xml",
        "views/house_estimator_views.xml",
        "views/website_lead_views.xml",
    ],
    "demo": ["demo/demo_data.xml"],
    "application": True,
}
